const headers = {
    headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
        Authorization: 'Bearer eyJraWQiOiJiODY1ZDJjNy1hYmM0LTQ4N2MtOGNkOS0zYTYzNGYwYjEyNjIiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzdGFyc2hpcCIsImF1ZCI6IlU1QlNIUE8xTEJIS0xGSE5SUlFNV0szS0pLTUhFVU9MM0hLVURUWFpQRUMiLCJuYmYiOjE3Mjg1Njg1MTQsInNjb3BlIjpbIkdBTUlORyJdLCJyb2xlcyI6WyJBRE1JTiJdLCJpc3MiOiJodHRwOi8vMTcyLjMxLjQuMTU0OjkwMTEiLCJleHAiOjE3MjkxNzMzMTQsImlhdCI6MTcyODU2ODUxNCwianRpIjoiYWNkNmQyODktNzg0Yy00NTkwLTg2NDYtNDY1YzFhMTVhMjAxIiwicHVibGljSWQiOiIxMjMifQ.Endyzt0vyVE9CZEXRj8SzG54bVtzkOV9XtixS8QUZ5lrsnLv3FWhWfBBbuCxkIY5wPDx_CHhSGbqbC3rEK0Kht7pdah_DixNA8-vf8B1DX1gCPOpCM1AwGbUvctC9mPpz48U5yTbVNhXKeVfH4vPF9HpeoB9s4tP__Zl-BRUZ9dgnu72XX2Oki8z_HRcX7F9cyp0B1cubkqUYjQ6kBALhDR3DQR6FEN9t_PBedSwcV4onnrOvtcImVgbvnd8bHl4da8vAF9vgVQaGJKzkMRS1NgJkqZBcqlnOK7sbJZaJQv7KW4c-Lq0VqnBtMu_rQtB9MNostFLMOq-3N5Uhe_59g'
    }
}

export { headers }